name: test suite
on: [push, pull_request]

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    env:
      LLVM_PROFILE_FILE: "bo-%p-%m.profraw"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Install protoc
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: protobuf-compiler
          version: 1.0

      - name: Cache Cargo registry
        id: cache-cargo-registry
        uses: actions/cache@v4
        with:
          path: /home/runner/.cargo/registry
          key: ${{ runner.os }}-cargo-registry

      - name: Cache Cargo build
        id: cache-cargo-build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build

      - name: Run tests
        run: cargo test --all-features
        env:
          RUSTFLAGS: -Cinstrument-coverage

      - name: Install grcov
        run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - name: Generate coverage report
        run: ./grcov . -s src --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/

      - name: Upload Badge
        uses: actions/upload-artifact@v4
        with:
          name: coverage-badges
          path: ./target/debug/coverage/badges/

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: ./target/debug/coverage/html/
